name: cd

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed
    branches:
      - "main"
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    # CIが成功した場合のみ実行する
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: debug
        run: |
          echo deploy
          ls
