name: cd

on:
  workflow_call:
    inputs:
      id:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: debug
        run: |
          echo deploy
          ls
          echo ${{secrets.password}}
          echo ${{inputs.id}}
