name: ci

on:
  pull_request:
  pull_request_target:
    branches:
      - "main"
      - "develop"

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: debug
        run: |
          echo test
          ls
          echo ${{github.event}}
